// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPaLPd_VB9S-cH2UtXsN4BPl_fSBbWvFw',
    appId: '1:951321330093:web:588d9e586c72ad32fde124',
    messagingSenderId: '951321330093',
    projectId: 'tik-tak-toe-eccf4',
    authDomain: 'tik-tak-toe-eccf4.firebaseapp.com',
    storageBucket: 'tik-tak-toe-eccf4.firebasestorage.app',
    measurementId: 'G-5J3WS5CVYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQTFafR5BkbVt2Y-8PFIeTz9-159Dlnc',
    appId: '1:951321330093:android:77f8c6f4a0191e11fde124',
    messagingSenderId: '951321330093',
    projectId: 'tik-tak-toe-eccf4',
    storageBucket: 'tik-tak-toe-eccf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvD-IUXoLbj0P6HAEM2x6WD92qtwpcRE8',
    appId: '1:951321330093:ios:b0ad3354a2355beefde124',
    messagingSenderId: '951321330093',
    projectId: 'tik-tak-toe-eccf4',
    storageBucket: 'tik-tak-toe-eccf4.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToev',
  );
}
